function opt= defopt_scalp_power2(varargin)
% in construction

opt= propertylist2struct(varargin{:});
opt= set_defaults(opt, ...
                  'Shading','flat', ...
                  'Extrapolation',1, ...
                  'ExtrapolateToMean', 0, ...
                  'Resolution', 61, ...
                  'CLim','range', ...
                  'IvalColor', [0.8 0.8 0.8; 0.6 0.6 0.6], ...
                  'LineWidth', 2, ...
                  'ChannelLineStyleOrder', {'thick','thin'}, ...
                  'Renderer', 'contourf', ...
                  'Colormap',cmap_hsv_fade(51, [4/6 0], 1, 1), ...
                  'Contour',5, ...
                  'ContourPolicy','strict', ...
                  'ContourLineprop',{'LineWidth',0.3}, ...
                  'MarkProperties',{'MarkerSize',6, 'LineWidth',1}, ...
                  'GlobalCLim',1, ...
                  'LegendPos','NorthEast');

