function opt= defopt_scalp_r2(varargin)
% in construction

opt= propertylist2struct(varargin{:});
opt= set_defaults(opt, ...
                  'Shading','flat', ...
                  'Extrapolation',1, ...
                  'ExtrapolateToMean',0, ...
                  'Resolution', 71, ...
                  'CLim','sym', ...
                  'ShrinkColorbar', 0.2, ...
                  'ColorOrder',[0 0 0], ...
                  'Colormap',cmap_posneg(51), ...
                  'LineWidth', 2, ...
                  'ChannelLineStyleOrder', {'thick','thin'}, ...
                  'IvalColor', [0.8 0.8 0.8; 0.6 0.6 0.6], ...
                  'Contour',5, ...
                  'ContourPolicy','withinrange', ...
                  'ContourLineprop',{'LineWidth',0.3}, ...
                  'MarkProperties',{'MarkerSize',6, 'LineWidth',1}, ...
                  'ChannelAtBottom', 1, ...
                  'GlobalCLim',1, ...
                  'Renderer', 'contourf', ...
                  'LegendPos','NorthWest');
