function opt= defopt_erps(varargin)
% in construction

opt= propertylist2struct(varargin{:});
opt= set_defaults(opt, ...
                  'LineWidth',0.7, ...
                  'AxisType','cross', ...
                  'AxisTitleVerticalAlignment', 'top', ...
                  'AxisTitleFontWeight', 'demi', ...
                  'ScaleHPos','left');
