function opt= defopt_scalp_erp2(varargin)
%DEFOPT_SCALP_ERP2 - Define
%


opt= propertylist2struct(varargin{:});
opt= set_defaults(opt, ...
                  'Shading','interp', ...
                  'Extrapolation',1, ...
                  'ExtrapolateToMean',0, ...
                  'Resolution', 71, ...
                  'CLim','sym', ...
                  'ShrinkColorbar', 0.2, ...
                  'Colormap',jet(51), ...
                  'Contour',5, ...
                  'LineWidth', 2, ...
                  'ChannelLineStyleOrder', {'thick','thin'}, ...
                  'IvalColor', [0.8 0.8 0.8; 0.6 0.6 0.6], ...
                  'ContourPolicy','strict', ...
                  'ContourLineprop',{'LineWidth',0.3}, ...
                  'MarkProperties',{'MarkerSize',6, 'LineWidth',1}, ...
                  'GlobalCLim',1, ...
                  'Renderer', 'contourf', ...
                  'LegendPos','NorthWest');
