function opt= defopt_scalp_erp(varargin)
% in construction

opt= propertylist2struct(varargin{:});
opt= set_defaults(opt, ...
                  'Shading','flat', ...
                  'Extrapolation',0, ...
                  'Resolution', 61, ...
                  'CLim','sym', ...
                  'Colormap',jet(51), ...
                  'Contour',5, ...
                  'ChannelLineStyleOrder', {'thick','thin'}, ...
                  'IvalColor', [0.8 0.8 0.8; 0.6 0.6 0.6], ...
                  'ContourPolicy','strict', ...
                  'ContourLineprop',{'LineWidth',0.3}, ...
                  'MarkProperties',{'MarkerSize',6, 'LineWidth',1}, ...
                  'GlobalCLim',1);
