function opt= defopt_scalp_csp(varargin)
% in construction

opt= propertylist2struct(varargin{:});
opt= set_defaults(opt, ...
                  'Shading','flat', ...
                  'Extrapolation',0, ...
                  'Resolution', 61, ...
                  'Linespec', {'LineWidth',2, 'Color','k'}, ...
                  'CLim','sym', ...
                  'ColorOrder',[0 0 0], ...
                  'Colormap',cmap_greenwhitelila(31), ...
                  'Contour',5, ...
                  'ContourPolicy','withinrange', ...
                  'ContourLineprop',{'LineWidth',0.3}, ...
                  'MarkProperties',{'MarkerSize',6, 'LineWidth',1}, ...
                  'GlobalCLim',1);
