function grd= util_gridForLaplacian
% UTIL_GRIDFORLAPLACIAN - Channel grid to define neighbors for Laplacians
%
%Synopsis:
%  grd= util_gridForLaplacian

% 09-2012 Benjamin Blankertz


str= [
      '  _     _     _     _   Fp1   Fpz   Fp2     _     _     _     _\n' ...
      '  <     _     _     _     _  AFp1  AFp2     _     _     _     _\n' ...
      'AF9   AF7   AF5   AF3   AF1   AFz   AF2   AF4   AF6   AF8  AF10\n' ...
      '  <  FAF9  FAF7  FAF5  FAF3  FAF1  FAF2  FAF4  FAF6  FAF8 FAF10\n' ...
      ' F9    F7    F5    F3    F1    Fz    F2    F4    F6    F8   F10\n' ...
      '  <  FFC9  FFC7  FFC5  FFC3  FFC1  FFC2  FFC4  FFC6  FFC8 FFC10\n' ...
      'FT9   FT7   FC5   FC3   FC1   FCz   FC2   FC4   FC6   FT8  FT10\n' ...
      '  <  CFC9  CFC7  CFC5  CFC3  CFC1  CFC2  CFC4  CFC6  CFC8 CFC10\n' ...
      ' T9    T7    C5    C3    C1    Cz    C2    C4    C6    T8   T10\n' ...
      '  <  CCP9  CCP7  CCP5  CCP3  CCP1  CCP2  CCP4  CCP6  CCP8 CCP10\n' ...
      'TP9   TP7   CP5   CP3   CP1   CPz   CP2   CP4   CP6   TP8  TP10\n' ...
      '  <  PCP9  PCP7  PCP5  PCP3  PCP1  PCP2  PCP4  PCP6  PCP8 PCP10\n' ...
      ' P9    P7    P5    P3    P1    Pz    P2    P4    P6    P8   P10\n' ...
      '  <  PPO9  PPO7  PPO5  PPO3  PPO1  PPO2  PPO4  PPO6  PPO8 PPO10\n' ...
      'PO9   PO7   PO5   PO3   PO1   POz   PO2   PO4   PO6   PO8  PO10\n' ...
      '  <     _     _     _     _  OPO1  OPO2     _     _     _     _\n' ...
      '  _     _     _    O9    O1    Oz    O2   O10     _     _     _\n' ...
      '  <     _     _     _     _   OI1   OI2     _     _     _     _\n' ...
      '  _     _     _     _     I1   Iz    I2     _     _     _     _'];

nCols= 11;
G= cell(1, nCols);
[G{:}]= strread(sprintf(str), repmat('%s', [1 nCols]));
grd= cat(2, G{:});
